GLSP-1009: Provide web-extension example
eclipse-glsp/glsp-vscode-integration pull request #39
Opened 2023-05-22 17:19 UTC by tortmayr

- Refactor codebase to provide entry points for both "normal" node VSCode extensions and web VSCode extensions. (via "@eclipse-glsp/vscode-integration/browser")
- Add additonal webview-extension example that covers two usecases
  - Communication with a GLSPServer that is running in the same extension context
  - Communication with a GLSPServer that is running externally via websocket
- Add launch configuration for starting the web extension

2023-05-26 13:30 UTC, martin-fleck-at requested changes
Great work, thank you very much Tobias! It works well, I just have a few questions about the structure. I also noticed that we skipped the Elk layouting here, so if that causes issues we should open a follow-up ticket for it.

2023-05-26 13:30 UTC, martin-fleck-at commented on example/workflow/web-extension/src/server/main.ts
> +export function createServerModules(): ContainerModule[] {
Could you please explain why this function is in a separate file? In the regular extension case, it is not and I don't see the benefit of it. Especially the name `main.ts` seems to imply that this is somehow compiled separately but I couldn't find anything related to it.

2023-05-26 13:30 UTC, martin-fleck-at commented on example/workflow/web-extension/src/workflow-extension.ts
> +        : new NodeGlspVscodeServer({
The name `NodeGlspVscodeServer` is a bit confusing.

2023-05-27 11:44 UTC, tortmayr commented
Thanks Martin, I have addressed your feedback.
The `NodeGlspVscodeServer` is now only used in the node context in web/brower its called `BrowserGlspVscodeServer`.
In addition, I have restructured the web extension server code into a single file `workflow-server.ts`

2023-05-27 11:50 UTC, merged