#234 Improve action handling flow
eclipse-glsp/glsp-vscode-integration pull request #6
Opened 2021-05-12 18:04 UTC by tortmayr

Introduce `GLSPVscodeExtensionActionHandler` that provides the delegation/dispatching of local actions from the webview to the vsode extension. This enables the implementation of action handlers that require access  to the vscode API and/or node backend.

Also:
+ cleanup and centralize command registration into the `GLSPEditorContext` instead of the editor provider.
+ Add `registerActionHandlers()` to `GLSPEditorContext` method that enables the registration of additional extension action handlers in the user space
- Move `extensionPrefix` from constructor into abstract property
- Fix typos

2021-05-12 18:44 UTC, planger requested changes
Thanks Tobias, looks great to me! Just a few style suggestions inline.

@lforst Can you please test whether this works for your use cases?

2021-05-12 18:44 UTC, planger commented on vscode-integration-webview/src/extension-action-handler.ts
> +    initialize(registry: ActionHandlerRegistry): void {
```suggestion

    initialize(registry: ActionHandlerRegistry): void {
```

2021-05-12 18:44 UTC, planger commented on vscode-integration-webview/src/extension-action-handler.ts
> +
```suggestion
```

2021-05-12 18:44 UTC, planger commented on vscode-integration-webview/src/extension-action-handler.ts
> +                _localDispatch: true
```suggestion
                __localDispatch: true
```

2021-05-12 18:44 UTC, planger commented on vscode-integration-webview/src/glsp-vscode-diagramserver.ts
> +export const localDispatchProperty = '_localDispatch';
```suggestion
export const localDispatchProperty = '__localDispatch';
```

2021-05-12 18:44 UTC, planger commented on vscode-integration/src/glsp-diagram-editor-context.ts
> +    }
```suggestion
    }

```

2021-05-13 08:45 UTC, tortmayr commented on vscode-integration-webview/src/extension-action-handler.ts
> +    initialize(registry: ActionHandlerRegistry): void {
Done

2021-05-13 08:45 UTC, tortmayr commented on vscode-integration/src/glsp-diagram-editor-context.ts
> +    }
Done

2021-05-13 16:30 UTC, lforst commented
> @lforst Can you please test whether this works for your use cases?

Works like a charm! Thanks for taking the time to implement this!

2021-05-13 20:42 UTC, planger approved these changes
Thanks, looks good to me! :+1:
Also, thanks @lforst for testing!

2021-05-14 10:13 UTC, merged